name: asset_manager
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  mason_logger: ^0.1.2
executables:
  asset_manager:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


flutter:    
