name: asset_manager_cli
description: Auto-generate the assets code and add it to your pubspec.yaml .
version: 0.1.0-dev.0+1
homepage: https://github.com/rutvik110/asset_manager
funding:
 - https://www.buymeacoffee.com/takrutvik

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  mason_logger: ^0.1.2
executables:
  asset_manager:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


